# Generated by Django 5.2.14 on 2026-06-02 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['origen', 'destino'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transporte.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transporte.conductor')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='transporte.ruta')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
